config/routes.rb
Rails.application.routes.draw do

  root  "home#index"

  get   "/pictures"            ,to: "pictures#index"    ,as: :pictures
  post  "/pictures"            ,to: "pictures#create"
  get   "/picture/:id"         ,to: "pictures#show"     ,as: :picture
  patch "/picture/:id"         ,to: "pictures#update"
  patch "/picture/:id/upvote"  ,to: "pictures#upvote"   ,as: :upvote_picture
  get   "/pictures/new"        ,to: "pictures#new"      ,as: :new_picture
  get   "/picture/:id/edit"    ,to: "pictures#edit"     ,as: :edit_picture
  patch "/picture/:id/edit"    ,to: "pictures#destroy"

  get   "/words"               ,to: "words#index"    ,as: :words
  post  "/words"               ,to: "words#create"
  get   "/word/:id"            ,to: "words#show"     ,as: :word
  patch "/word/:id"            ,to: "words#update"
  patch "/word/:id/upvote"     ,to: "words#upvote"   ,as: :upvote_word
  get   "/words/new"           ,to: "words#new"      ,as: :new_word
  get   "/word/:id/edit"       ,to: "words#edit"     ,as: :edit_word
  patch "/word/:id/edit"       ,to: "words#destroy"

  get   "/albums"              ,to: "albums#index"    ,as: :albums
  post  "/albums"              ,to: "albums#create"
  get   "/album/:id"           ,to: "albums#show"     ,as: :album
  patch "/album/:id"           ,to: "albums#update"
  patch "/album/:id/upvote"    ,to: "albums#upvote"   ,as: :upvote_album
  get   "/albums/new"          ,to: "albums#new"      ,as: :new_album
  get   "/album/:id/edit"      ,to: "albums#edit"     ,as: :edit_album
  patch "/album/:id/edit"      ,to: "albums#destroy"

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :uploader, PictureUploadUploader
end

app/models/word.rb
class Word < ActiveRecord::Base

  def sort

  end
  

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @album = Album.all

  end

  def new
    @album = Album.new

  end

  def create
    if Album.create(album_params)
      redirect_to root_path
    end
  end

  def show
    find_album
  end

  def edit
    find_album
  end

  def update
    if @album = find_album.update(album_params)
      redirect_to album_path
    end
  end

  def upvote
    # if upvote button is pressed than the ranking increased by 1
      find_album.update(ranking: @album.ranking + 1)
      redirect_to album_path
  end

  def destroy
    if find_album.destroy
      redirect_to albums_path
    end
  end


  private

  def album_params
    params.require(:album).permit(:name, :recorder, :description, :ranking)
  end

  def find_album
    @album = Album.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @word = Word.all # get top ten
    @album = Album.all
    @picture= Picture.all
  end

  def create

  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @picture = Picture.all

  end

  def new
    @picture = Picture.new

  end

  def create
     if Picture.create(picture_params)
       # uploader = PictureUploadUploader
       redirect_to root_path
     end
  end

  def show
    find_picture
  end

  def edit
    find_picture
  end

  def update
    if @picture = find_picture.update(picture_params)
      redirect_to picture_path
    end
  end

  def upvote
    # if upvote button is pressed than the ranking increased by 1
      find_picture.update(ranking: @picture.ranking + 1)
      redirect_to picture_path
  end

  def destroy
    if find_picture.destroy
      redirect_to pictures_path
    end
  end


  private

  def picture_params
    params.require(:picture).permit(:name, :url, :description, :ranking, :uploader)
  end

  def find_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @word = Word.all

  end

  def new
    @word = Word.new

  end

  def create
    if Word.create(word_params)
      redirect_to root_path
    end
  end

  def show
    find_word
  end

  def edit
    find_word
  end

  def update
    if @word = find_word.update(word_params)
      redirect_to word_path
    end
  end

  def upvote
    # if upvote button is pressed than the ranking increased by 1
      find_word.update(ranking: @word.ranking + 1)
      redirect_to word_path
  end

  def destroy
    if find_word.destroy
      redirect_to words_path
    end
  end


  private

  def word_params
    params.require(:word).permit(:word, :language, :definition, :ranking)
  end

  def find_word
    @word = Word.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<%= form_for @album do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :recorder %>
    <%= f.text_field :recorder %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>


    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/albums/index.html.erb
<!-- list all the memes here-->
<!-- add button that adds new meme to data base -->
<!-- have a link that directs back to homepage -->

<!-- list all the album here-->
<!-- add button that adds new album to data base -->
<!-- have a link that directs back to homepage -->
<!--  create a table table to show all albums, language, definition, ect-->

<h2>albums</h2>
<table class="table-hover table-responsive col-sm-12">
    <tr>
      <th>Ranking</th>
      <th>Name</th>
      <th>Upvote</th>
    </tr>

<% @album.each do |album| %>
    <tr>
      <td>Ranked:<%= album.ranking %></td>
      <td><%= link_to album.name, album_path(album.id)  %></td>
      <td><%= button_to "Upvote", upvote_album_path(album), method: :patch %></td>
    </tr>
<% end %>
  </table>

<%= button_to "Add album", new_album_path, method: :get %>
<%= button_to "Home", root_path, method: :get %>

app/views/albums/new.html.erb
<h1>AHHHH NEW album FORM</h1>

<%= form_for @album do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :recorder %>
    <%= f.text_field :recorder %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>

    <%= f.hidden_field(:ranking, value: 0) %>

    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/albums/show.html.erb
<!-- this page show indivual albums based on id -->

<h1><%= @album.name %></h1>
<h2><%= @album.recorder %></h3>
<h3><%= @album.description %></h2>
<h4>Ranking: <%= @album.ranking %></h4>

<%= button_to "Upvote", upvote_album_path(@album), method: :patch %>
<%= button_to "Edit", edit_album_path, method: :get %>
<%= button_to "Delete", edit_album_path, method: :patch %>
<%= button_to "All albums", albums_path, method: :get %>
<%= button_to "Home", root_path, method: :get %>

app/views/home/index.html.erb
<!-- This page will list a few things from each catorgory with a link that will list more -->

<body>
  <div class="links">
    <%= link_to "Add Word", new_word_path, method: :get %>
    <%= link_to "Add Picture", new_picture_path, method: :get %>
    <%= link_to "Add Album", new_album_path, method: :get %>

  </div>
<div class="container">
<span class="homeIndex">
  <div class="col-md-4">
    <h2>Words</h2>

    <%@word.each do |word| %>
      <h3 class="words"><%= link_to(word.word, word_path(word.id)) %></h3>
    <%end %>
  </div>

  <div class="col-md-4">
    <h2>Pictures</h2>
    <%@picture.each do |picture| %>
      <a class="pictures" href="<%= picture_path(picture.id) %>" >
    <%#= image_tag picture.uploader_url.to_s %>
      <img src="<%= picture.url %>" alt="<%= picture.name %>" height="60" width="60" class="img-circle"/></a>
    <%end %>
  </div>

  <div class="col-md-4">
    <h2>Albums</h2>
    <%@album.each do |album| %>
      <h3 class="albums"><%= link_to(album.name, album_path(album.id)) %></h3>
    <%end %>
  </div>

</span>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Amatic+SC' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'>
  <title>Ranker of the Things</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 class="header"><%=link_to "Ranker Thingy", root_path , :class => "heading"%></h1>

<h3 class="headerDescription">A collection of very important things...</h3>

<%= yield %>

</body>
</html>

app/views/memes/edit.html.erb
<h1>Edit <%= @meme.name %></h1>


<%= form_for @meme do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :author %>
    <%= f.text_field :author %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>


    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/memes/new.html.erb
<h1>AHHHH NEW meme FORM</h1>

app/views/pictures/edit.html.erb
<h1>Edit <%= @picture.name %></h1>


<%= form_for @picture do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :url %>
    <%= f.text_field :url %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>


    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/pictures/index.html.erb
<!-- list all the pictures here-->
<!-- add button that adds new picture to data base -->
<!-- have a link that directs back to homepage -->

<!-- list all the picture here-->
<!-- add button that adds new picture to data base -->
<!-- have a link that directs back to homepage -->
<!--  create a table table to show all pictures, language, definition, ect-->

<h2>Pictures</h2>
<table class="table-hover table-responsive col-sm-12">
    <tr>
      <th>Ranking</th>
      <th>Name</th>
      <th>Upvote</th>
    </tr>

<% @picture.each do |picture| %>
    <tr>
      <td>Ranked:<%= picture.ranking %></td>
      <td><%= link_to picture.name, picture_path(picture.id)  %></td>
      <td><%= button_to "Upvote", upvote_picture_path(picture), method: :patch %></td>
    </tr>
<% end %>
  </table>

<%= button_to "Add picture", new_picture_path, method: :get %>
<%= button_to "Home", root_path, method: :get %>

app/views/pictures/new.html.erb
<h1>AHHHH New Picture Form</h1>


<%= form_for @picture, :html => {:multipart => true} do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :url %>
    <%= f.text_field :url %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>

    <%= f.file_field :uploader %><br>

    <%= f.label :remote_uploader_url, "Or image url" %>
    <%= f.text_field :remote_uploader_url %><br>

    <%= f.hidden_field(:ranking, value: 0) %>

    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/pictures/show.html.erb
<!-- this page show indivual pictures based on id -->
<!-- this page show indivual pictures based on id -->

<h1><%= @picture.name %></h1>
<h3><img src="<%= @picture.url %>" alt="<%= @picture.name %>" height="250" width="250">
</h3>
<h2><%= @picture.description %></h2>
<h4>Ranking: <%= @picture.ranking %></h4>

<%= button_to "Upvote", upvote_picture_path(@picture), method: :patch %>
<%= button_to "Edit", edit_picture_path, method: :get %>
<%= button_to "Delete", edit_picture_path, method: :patch %>
<%= button_to "All Pictures", pictures_path, method: :get %>
<%= button_to "Home", root_path, method: :get %>

app/views/words/edit.html.erb
<h1>Edit <%= @word.word %></h1>

<%= form_for @word do |f| %>

    <%= f.label :word %>
    <%= f.text_field :word %><br>

    <%= f.label :language %>
    <%= f.text_field :language %><br>

    <%= f.label :definition %>
    <%= f.text_field :definition %><br>


    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/words/index.html.erb
<!-- list all the word here-->
<!-- add button that adds new word to data base -->
<!-- have a link that directs back to homepage -->
<!--  create a table table to show all words, language, definition, ect-->

<h2>Words</h2>
<table class="table-hover table-responsive col-sm-12">
    <tr>
      <th>Ranking</th>
      <th>Name</th>
      <th>Upvote</th>
    </tr>

<% @word.each do |word| %>
    <tr>
      <td>Ranked:<%= word.ranking %></td>
      <td><%= link_to word.word, word_path(word.id)  %></td>
      <td><%= button_to "Upvote", upvote_word_path(word), method: :patch %></td>
    </tr>
<% end %>
  </table>

<%= button_to "Add Word", new_word_path, method: :get %>
<%= button_to "Home", root_path, method: :get %>

app/views/words/new.html.erb
<h1>AHHHH NEW WORD FORM</h1>

<%= form_for @word do |f| %>

    <%= f.label :word %>
    <%= f.text_field :word %><br>

    <%= f.label :language %>
    <%= f.text_field :language %><br>

    <%= f.label :definition %>
    <%= f.text_field :definition %><br>

    <%= f.hidden_field(:ranking, value: 0) %>

    <%= f.submit "Submit" %>
    <!-- it defaults to the restful route that it is in, it used reasoures -->
  <% end %>

app/views/words/show.html.erb
<!-- this page show indivual words based on id -->
<div class="container">
  <div>
    <h1><%= @word.word %></h1>
    <h2><%= @word.language %></h3>
    <h3><%= @word.definition %></h2>
    <h4>Ranking : <%= @word.ranking %></h4>
  </div>

  <!-- <div class="buttons"> -->
    <!-- <button class="btn btn-default" > -->
    <%= button_to "Upvote", upvote_word_path(@word), method: :patch %>
    <%= button_to "Edit", edit_word_path, method: :get %>
    <%= button_to "Delete", edit_word_path, method: :patch %>
    <%= button_to "All Words", words_path, method: :get %>
  <%= button_to   "Home", root_path, method: :get %>
  <!-- </button> -->
<!-- </div> -->

</div>